JOB_NAMES = [
    "大模型应用工程师",
    "AI 智能体开发工程师",
    "数据分析师",
    "数据治理工程师",
    "算法工程师",
    "Java 开发工程师",
    "前端开发工程师",
    "物联网开发工程师",
    "智能系统工程师",
    "机器学习工程师",
    "AI 产品经理",
    "数据产品经理",
    "网络安全分析师",
    "数字化解决方案顾问",
    "数据资产运营专员",
    "AIGC 内容风控分析师",
    "智能制造实施顾问",
    "低代码平台配置顾问",
]

JOB_PROFILES = {
    "大模型应用工程师": {
        "domain": "人工智能",
        "job_type": "新兴技术研发",
        "level": "中级",
        "description": "岗位职责：负责企业知识库问答、智能客服、文档检索、报告生成等大模型应用的需求分析、方案设计和后端开发；搭建 RAG 检索链路，完成向量化、召回、重排序、Prompt 模板和接口封装；配合产品和业务团队评估回答准确率、响应时延和用户反馈。任职要求：熟悉 Python、FastAPI、LangChain、RAG、向量数据库和 RESTful API，理解提示词工程、知识切片、召回评估和基础模型调用流程；具备 Docker、Linux、Git 基础工程化能力。加分项：有企业知识库、智能问答、流程自动化或 LLMOps 项目经验，能为模型输出提供 evidence 和可追溯日志。",
        "is_emerging": True,
    },
    "AI 智能体开发工程师": {
        "domain": "人工智能",
        "job_type": "新兴技术研发",
        "level": "高级",
        "description": "岗位职责：负责多智能体任务拆解、工具调用、工作流编排和执行状态管理，建设面向业务流程的智能体平台能力；设计任务规划、记忆管理、函数调用、异常回退和人机协同审核机制。任职要求：熟悉 Python、LangChain、RAG、Prompt Engineering、工作流引擎、OpenAPI 和权限控制，理解智能体调用链路的安全边界和可观测性要求。加分项：有客服、运营、数据分析、办公自动化等智能体落地经验，能设计低置信度转人工的闭环流程。",
        "is_emerging": True,
    },
    "数据分析师": {
        "domain": "数据技术",
        "job_type": "数据分析",
        "level": "中级",
        "description": "岗位职责：围绕业务指标体系开展数据提取、清洗、分析和可视化，输出经营分析、用户画像、转化漏斗、活动复盘和专题报告；支持业务部门定位问题、验证假设并提出数据化建议。任职要求：熟悉 SQL、Python、Pandas、统计分析、BI 分析、数据可视化和 A/B 测试，能独立完成指标口径梳理和报表建设。加分项：了解行业业务流程，有用户增长、风控、供应链或教育运营分析经验。",
        "is_emerging": False,
    },
    "数据治理工程师": {
        "domain": "数据技术",
        "job_type": "数据治理",
        "level": "高级",
        "description": "岗位职责：负责数据标准、元数据、数据血缘、数据质量、主数据和数据资产目录建设，推动跨系统数据口径统一和治理规则落地；设计质量稽核任务、异常告警和整改闭环。任职要求：熟悉 SQL、Hive、Spark、数据仓库、元数据管理、数据血缘、数据质量和数据安全合规，具备跨部门沟通和治理制度沉淀能力。加分项：有政务、金融、制造或集团型企业数据治理项目经验。",
        "is_emerging": False,
    },
    "算法工程师": {
        "domain": "人工智能",
        "job_type": "算法研发",
        "level": "高级",
        "description": "岗位职责：负责机器学习、深度学习、推荐、NLP 或计算机视觉模型的特征构建、训练、评估、调优和上线效果跟踪；与工程团队协作完成模型服务化和监控。任职要求：熟悉 Python、PyTorch、TensorFlow、Scikit-learn、特征工程、模型评估和实验管理，理解过拟合、数据偏差、指标选择和模型迭代流程。加分项：有线上推荐、风控、搜索、视觉质检或文本分类项目经验。",
        "is_emerging": False,
    },
    "Java 开发工程师": {
        "domain": "软件研发",
        "job_type": "后端研发",
        "level": "中级",
        "description": "岗位职责：负责业务系统后端接口、服务拆分、数据库设计、缓存、消息队列和系统性能优化；参与需求评审、接口联调、测试修复和上线运维。任职要求：熟悉 Java、Spring Boot、Spring Cloud、MySQL、Redis、Kafka、RESTful API 和 Git，理解事务、并发、索引优化和微服务治理。加分项：具备高并发业务、权限体系、订单流程或数据中台接口开发经验。",
        "is_emerging": False,
    },
    "前端开发工程师": {
        "domain": "软件研发",
        "job_type": "前端研发",
        "level": "中级",
        "description": "岗位职责：负责 Web 管理端、数据分析页面和可视化交互模块开发，建设组件、路由、状态管理、接口联调和页面性能优化。任职要求：熟悉 Vue、React、TypeScript、Element Plus、ECharts、AntV G6、前端工程化和响应式布局，能处理复杂表格、图谱、表单和权限菜单。加分项：有数据可视化、低代码配置平台或复杂后台系统开发经验。",
        "is_emerging": False,
    },
    "物联网开发工程师": {
        "domain": "物联网",
        "job_type": "设备与边缘开发",
        "level": "中级",
        "description": "岗位职责：负责设备接入、协议解析、边缘采集、数据上报和平台联调，支持传感器、网关、设备状态监测和异常告警场景。任职要求：熟悉 MQTT、Linux、嵌入式 Linux、传感器数据处理、Docker、消息队列和基础网络协议，能定位设备连接、数据丢包和边缘部署问题。加分项：有工业物联网、智慧园区、能源监测或智能制造现场项目经验。",
        "is_emerging": False,
    },
    "智能系统工程师": {
        "domain": "智能系统",
        "job_type": "系统集成",
        "level": "高级",
        "description": "岗位职责：负责智能硬件、算法服务、业务平台和数据链路的整体方案集成，完成需求调研、系统设计、联调测试、部署交付和运行评估。任职要求：熟悉 Python、Linux、Docker、边缘计算、模型部署、RESTful API 和系统监控，具备跨硬件、算法、平台团队协作能力。加分项：有智慧城市、智能制造、校园安全或工业质检系统集成经验。",
        "is_emerging": True,
    },
    "机器学习工程师": {
        "domain": "人工智能",
        "job_type": "算法工程化",
        "level": "中级",
        "description": "岗位职责：负责机器学习模型的数据准备、训练评估、特征迭代、服务部署和效果监控，推动模型从实验环境进入业务系统。任职要求：熟悉 Python、机器学习、Scikit-learn、PyTorch、模型评估、模型部署、Docker 和 Linux，能够编写稳定的数据处理和训练脚本。加分项：有风控评分、预测分析、文本分类或推荐系统项目经验。",
        "is_emerging": False,
    },
    "AI 产品经理": {
        "domain": "人工智能",
        "job_type": "产品与策略",
        "level": "中级",
        "description": "岗位职责：负责 AI 应用的用户需求调研、场景拆解、功能设计、Prompt 体验评估、效果指标定义和版本迭代；协调算法、研发、设计、运营和业务方推进落地。任职要求：理解大模型、RAG、智能体、数据标注、模型评估和人机协同流程，具备 PRD、原型、验收标准和上线复盘能力。加分项：有智能客服、知识库、AIGC 工具、数据产品或 ToB 产品经验。",
        "is_emerging": True,
    },
    "数据产品经理": {
        "domain": "数据技术",
        "job_type": "产品与策略",
        "level": "中级",
        "description": "岗位职责：负责指标体系、数据门户、资产目录、BI 看板和数据服务能力规划，推动数据从采集、治理到应用的产品化。任职要求：熟悉 SQL、数据仓库、元数据管理、数据质量、BI 分析和用户需求分析，能设计清晰的数据口径、权限和使用流程。加分项：有经营分析平台、数据中台、数据资产管理或自助分析产品经验。",
        "is_emerging": False,
    },
    "网络安全分析师": {
        "domain": "安全合规",
        "job_type": "安全运营",
        "level": "中级",
        "description": "岗位职责：负责日志监控、告警分析、漏洞跟踪、风险研判和安全事件响应，协助完善安全基线、权限审计和合规检查。任职要求：熟悉 Linux、网络协议、日志分析、权限管理、安全合规、应急响应和报告编写，具备基本脚本处理能力。加分项：了解等保、数据安全、云安全或安全运营平台建设。",
        "is_emerging": False,
    },
    "数字化解决方案顾问": {
        "domain": "产业数字化",
        "job_type": "解决方案",
        "level": "高级",
        "description": "岗位职责：面向制造、教育、政务、金融等客户开展业务调研、痛点分析、方案设计、标书支持和交付协同，形成数字化转型方案。任职要求：理解数据治理、系统集成、AI 应用、云原生和项目管理，具备客户沟通、方案表达和跨团队推进能力。加分项：有售前、咨询、行业解决方案或大型项目交付经验。",
        "is_emerging": False,
    },
    "数据资产运营专员": {
        "domain": "数据技术",
        "job_type": "数据运营",
        "level": "初级",
        "description": "岗位职责：负责数据资产登记、目录维护、标签完善、数据申请流转、使用统计和价值评估，推动数据资源被业务部门可见、可用和可追踪。任职要求：熟悉数据资产、元数据、数据质量、Excel/BI、SQL 基础和流程运营，具备细致的文档整理和跨部门沟通能力。加分项：了解数据要素、数据资产入表或数据交易相关概念。",
        "is_emerging": True,
    },
    "AIGC 内容风控分析师": {
        "domain": "安全合规",
        "job_type": "内容安全",
        "level": "中级",
        "description": "岗位职责：负责 AIGC 内容审核规则、风险标签、样本复核、策略评估和误杀漏放分析，协助产品与算法团队优化内容安全策略。任职要求：理解 AIGC 生成机制、内容审核流程、数据标注、规则策略、统计分析和安全合规要求，能输出清晰的复盘报告。加分项：有内容平台、社区治理、模型安全或风控策略经验。",
        "is_emerging": True,
    },
    "智能制造实施顾问": {
        "domain": "产业数字化",
        "job_type": "实施交付",
        "level": "中级",
        "description": "岗位职责：负责制造企业 MES、设备采集、生产看板、质量追溯和工艺数据项目的现场调研、配置实施、用户培训和上线支持。任职要求：理解制造流程、设备数据、物联网协议、数据可视化和项目交付管理，能协调客户、研发和现场人员解决问题。加分项：有工厂数字化、工业物联网或智能制造项目经验。",
        "is_emerging": False,
    },
    "低代码平台配置顾问": {
        "domain": "软件研发",
        "job_type": "平台配置",
        "level": "初级",
        "description": "岗位职责：基于低代码平台完成表单、流程、权限、数据模型和报表配置，支持客户快速搭建业务应用并进行培训交付。任职要求：熟悉业务流程梳理、权限管理、数据建模、接口配置和基础 SQL，具备较强的沟通、文档和问题排查能力。加分项：有 OA、CRM、项目管理、审批流或企业应用配置经验。",
        "is_emerging": False,
    },
}

EXTRA_JOB_PROFILES = {
    "云计算架构师": {
        "domain": "云计算",
        "job_type": "架构设计",
        "level": "高级",
        "description": "岗位职责：负责企业云平台、混合云、容器平台和云上应用架构规划，完成上云评估、网络与安全边界设计、成本测算、容量规划和高可用方案落地；指导研发与运维团队完成云资源编排、监控告警、容灾备份和性能优化。任职要求：熟悉 Kubernetes、Docker、Linux、CI/CD、Nginx、Prometheus、Grafana、云安全和微服务治理，理解公有云、私有云、混合云和多云管理模式。加分项：具备 AWS、Azure、Google Cloud、华为云、阿里云或腾讯云架构认证，有大型系统迁移和成本优化经验。",
        "is_emerging": False,
    },
    "DevOps 平台工程师": {
        "domain": "软件研发",
        "job_type": "研发效能",
        "level": "中级",
        "description": "岗位职责：建设代码管理、流水线、制品库、自动化测试、环境发布和质量门禁能力，提升研发交付效率；负责 CI/CD 模板、容器镜像规范、部署脚本、回滚策略和发布审计。任职要求：熟悉 Git、Docker、Kubernetes、Linux、Nginx、Prometheus、Grafana、脚本开发和微服务部署，能定位构建失败、依赖冲突、发布异常和环境漂移问题。加分项：有研发效能平台、灰度发布、蓝绿发布或多环境治理经验。",
        "is_emerging": False,
    },
    "SRE 站点可靠性工程师": {
        "domain": "云计算",
        "job_type": "稳定性保障",
        "level": "高级",
        "description": "岗位职责：负责核心业务系统稳定性建设，制定 SLI/SLO、容量模型、故障演练、应急预案和根因复盘机制；建设监控、日志、链路追踪和自动化运维工具，降低故障恢复时间。任职要求：熟悉 Linux、Kubernetes、Prometheus、Grafana、Nginx、微服务、CI/CD、脚本开发和日志分析，具备线上问题定位和跨团队推动能力。加分项：有大流量业务、金融级高可用系统或混沌工程经验。",
        "is_emerging": False,
    },
    "数据库管理员 DBA": {
        "domain": "数据技术",
        "job_type": "数据库运维",
        "level": "中级",
        "description": "岗位职责：负责 MySQL、Redis、ClickHouse、Hive 等数据库的安装配置、权限管理、备份恢复、性能优化、慢 SQL 分析、容量规划和数据安全审计；支持业务系统上线评审与故障处理。任职要求：熟悉 SQL、MySQL、Redis、Linux、数据仓库、ETL、数据质量和安全合规，能够编写巡检脚本并输出优化报告。加分项：了解高可用架构、分库分表、数据库迁移和云数据库运维。",
        "is_emerging": False,
    },
    "网络工程师": {
        "domain": "基础设施",
        "job_type": "网络运维",
        "level": "中级",
        "description": "岗位职责：负责园区网、数据中心网络、VPN、无线网络和安全设备的规划、部署、巡检与故障处理，保障业务系统网络稳定性。任职要求：熟悉网络协议、Linux、日志分析、安全合规、权限管理和基础脚本，能定位连通性、延迟、丢包、DNS 和路由策略问题。加分项：具备 Cisco、华为 Datacom 或网络安全相关认证，有云网络和多地域互联经验。",
        "is_emerging": False,
    },
    "云安全顾问": {
        "domain": "安全合规",
        "job_type": "安全咨询",
        "level": "高级",
        "description": "岗位职责：面向客户云上业务开展安全评估、基线检查、权限治理、日志审计、数据保护和合规整改，输出安全架构方案与落地路线。任职要求：熟悉安全合规、权限管理、日志分析、云安全、Kubernetes、Linux、数据安全和项目管理，能够将风险转化为可执行的整改清单。加分项：具备 CISP、CISSP、CCSP、Security+ 或云安全认证，有等保、数据安全或金融行业项目经验。",
        "is_emerging": True,
    },
    "渗透测试工程师": {
        "domain": "安全合规",
        "job_type": "攻防测试",
        "level": "中级",
        "description": "岗位职责：负责 Web、API、移动端、内网和云环境的安全测试，完成漏洞验证、风险评级、复测闭环和安全报告编写；协助研发修复常见安全问题。任职要求：熟悉 Linux、网络协议、脚本开发、日志分析、安全合规、权限管理和常见漏洞原理，具备清晰的证据链整理能力。加分项：具备 CEH、OSCP、CISP-PTE 或攻防演练经验。",
        "is_emerging": False,
    },
    "测试开发工程师": {
        "domain": "软件研发",
        "job_type": "质量保障",
        "level": "中级",
        "description": "岗位职责：建设接口测试、自动化回归、性能测试、测试数据管理和质量度量体系，参与需求评审、测试计划、缺陷定位和上线质量评估。任职要求：熟悉 Python、Java、SQL、RESTful API、Docker、Git、CI/CD、日志分析和测试自动化，能编写稳定的自动化脚本和质量报告。加分项：有微服务、数据平台或 AI 应用测试经验。",
        "is_emerging": False,
    },
    "数据仓库工程师": {
        "domain": "数据技术",
        "job_type": "数仓建设",
        "level": "中级",
        "description": "岗位职责：负责数据仓库分层建模、ETL 开发、指标口径治理、数据质量校验和任务调度，支撑 BI、经营分析和数据服务。任职要求：熟悉 SQL、Hive、Spark、Flink、Kafka、Airflow、数据仓库、ETL、元数据管理、数据血缘和数据质量，能根据业务过程设计清晰的数据模型。加分项：有实时数仓、湖仓一体或数据中台项目经验。",
        "is_emerging": False,
    },
    "BI 可视化分析师": {
        "domain": "数据技术",
        "job_type": "数据分析",
        "level": "中级",
        "description": "岗位职责：负责经营指标体系、管理看板、专题分析和自助取数模型建设，帮助业务部门发现问题并跟踪改善效果。任职要求：熟悉 SQL、BI 分析、统计分析、数据可视化、ECharts、用户画像、A/B 测试和需求分析，具备清晰的指标拆解和表达能力。加分项：熟悉 Tableau、Power BI、FineBI 或 Superset，有增长、运营、供应链或财务分析经验。",
        "is_emerging": False,
    },
    "IT 项目经理": {
        "domain": "产业数字化",
        "job_type": "项目管理",
        "level": "高级",
        "description": "岗位职责：负责 IT 项目的范围、进度、成本、质量、风险和干系人管理，推动需求评审、方案确认、研发联调、用户验收和上线交付。任职要求：熟悉项目管理、需求分析、业务流程建模、客户调研、安全合规和系统集成流程，能够协调产品、研发、测试、实施和客户团队。加分项：具备 PMP、软考信息系统项目管理师或大型 ToB 项目经验。",
        "is_emerging": False,
    },
    "ERP 实施顾问": {
        "domain": "产业数字化",
        "job_type": "实施交付",
        "level": "中级",
        "description": "岗位职责：负责企业财务、供应链、生产、库存、人力等 ERP 模块调研、蓝图设计、系统配置、数据迁移、用户培训和上线支持。任职要求：熟悉业务流程建模、需求分析、SQL、数据质量、项目管理、客户调研和实施交付，能将业务规则转化为系统配置方案。加分项：有制造、零售、医药或集团企业 ERP 项目经验。",
        "is_emerging": False,
    },
    "售前技术顾问": {
        "domain": "产业数字化",
        "job_type": "解决方案",
        "level": "中级",
        "description": "岗位职责：配合销售开展客户调研、需求澄清、方案编写、产品演示、标书响应和 PoC 验证，输出可落地的技术路线与交付边界。任职要求：熟悉客户调研、售前方案、需求分析、项目管理、数据治理、AI 应用、云原生和安全合规，具备优秀的表达和文档能力。加分项：有政企、教育、制造、金融或园区数字化售前经验。",
        "is_emerging": False,
    },
    "UI/UX 设计师": {
        "domain": "软件研发",
        "job_type": "体验设计",
        "level": "中级",
        "description": "岗位职责：负责 Web、移动端和后台系统的信息架构、交互流程、视觉规范、设计组件和可用性验证，与产品和前端团队协作提升用户体验。任职要求：熟悉产品设计、需求分析、用户画像、数据可视化、业务流程建模和设计系统，能输出原型、设计稿、交互说明和验收标准。加分项：有复杂后台、数据可视化、AI 工具或 ToB 产品设计经验。",
        "is_emerging": False,
    },
    "数据标注项目经理": {
        "domain": "人工智能",
        "job_type": "数据运营",
        "level": "中级",
        "description": "岗位职责：负责文本、图像、语音、多模态数据标注项目的需求拆解、规范制定、样本抽检、质量评估、人员排班和交付复盘，保障模型训练数据质量。任职要求：熟悉数据标注、数据质量、统计分析、内容审核、项目管理、Prompt Engineering 和安全合规，能建立一致性评估和质量闭环。加分项：有大模型、自动驾驶、医疗影像或内容安全标注项目经验。",
        "is_emerging": True,
    },
    "技术支持工程师": {
        "domain": "软件研发",
        "job_type": "客户支持",
        "level": "初级",
        "description": "岗位职责：负责客户问题受理、日志收集、故障定位、知识库维护、版本反馈和现场支持，协助研发复现并闭环产品问题。任职要求：熟悉 Linux、SQL、RESTful API、日志分析、权限管理、数据可视化和客户沟通，能够编写清晰的问题记录和解决方案。加分项：有企业软件、数据平台、云服务或硬件设备支持经验。",
        "is_emerging": False,
    },
}

JOB_PROFILES.update(EXTRA_JOB_PROFILES)
JOB_NAMES.extend(EXTRA_JOB_PROFILES.keys())

SKILLS = [
    "Python",
    "Java",
    "SQL",
    "MySQL",
    "Redis",
    "Docker",
    "Kubernetes",
    "Spring Boot",
    "Spring Cloud",
    "Vue",
    "React",
    "FastAPI",
    "Flask",
    "机器学习",
    "深度学习",
    "RAG",
    "Prompt Engineering",
    "LangChain",
    "向量数据库",
    "知识图谱",
    "数据治理",
    "数据血缘",
    "元数据管理",
    "数据质量",
    "Hadoop",
    "Spark",
    "Flink",
    "Kafka",
    "Hive",
    "Linux",
    "Git",
    "TypeScript",
    "Element Plus",
    "ECharts",
    "AntV G6",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "PyTorch",
    "TensorFlow",
    "NLP",
    "计算机视觉",
    "特征工程",
    "模型评估",
    "A/B 测试",
    "数据仓库",
    "ETL",
    "Airflow",
    "ClickHouse",
    "Elasticsearch",
    "Neo4j",
    "Milvus",
    "Faiss",
    "OpenAPI",
    "RESTful API",
    "微服务",
    "消息队列",
    "CI/CD",
    "Nginx",
    "Prometheus",
    "Grafana",
    "物联网协议",
    "MQTT",
    "边缘计算",
    "传感器数据处理",
    "嵌入式 Linux",
    "数据可视化",
    "BI 分析",
    "统计分析",
    "用户画像",
    "推荐系统",
    "强化学习",
    "模型部署",
    "模型压缩",
    "ONNX",
    "LLMOps",
    "智能体编排",
    "工作流引擎",
    "权限管理",
    "安全合规",
    "需求分析",
    "产品设计",
    "业务流程建模",
    "内容审核",
    "风险策略",
    "数据资产运营",
    "项目管理",
    "客户调研",
    "数据标注",
    "日志分析",
    "售前方案",
    "实施交付",
]

EXTRA_SKILLS = [
    "云计算架构",
    "DevOps",
    "SRE",
    "数据库运维",
    "网络协议",
    "云安全",
    "渗透测试",
    "漏洞扫描",
    "测试自动化",
    "性能测试",
    "实时数仓",
    "湖仓一体",
    "Tableau",
    "Power BI",
    "FineBI",
    "ERP 实施",
    "售前方案",
    "UI/UX 设计",
    "Figma",
    "数据标注管理",
    "ITIL",
]

for skill in EXTRA_SKILLS:
    if skill not in SKILLS:
        SKILLS.append(skill)

TOOLS = ["Docker", "Kubernetes", "Git", "Linux", "Kafka", "Hive", "Milvus", "Neo4j", "ECharts", "AntV G6"]
CERTIFICATE_GROUPS = {
    "国内软考与项目管理": [
        "软考 程序员",
        "软考 软件设计师",
        "软考 软件评测师",
        "软考 网络工程师",
        "软考 数据库系统工程师",
        "软考 信息安全工程师",
        "软考 系统集成项目管理工程师",
        "软考 信息系统项目管理师",
        "软考 系统架构设计师",
        "软考 系统分析师",
        "PMP 项目管理专业人士",
        "CAPM 助理项目管理专业人士",
        "PMI-ACP 敏捷认证",
        "PRINCE2 Foundation",
        "PRINCE2 Practitioner",
        "ITIL 4 Foundation",
        "NPDP 产品经理国际资格认证",
        "ScrumMaster CSM",
        "Professional Scrum Master I",
        "Professional Scrum Product Owner I",
    ],
    "云计算与云厂商认证": [
        "AWS Certified Cloud Practitioner",
        "AWS Certified AI Practitioner",
        "AWS Certified Solutions Architect - Associate",
        "AWS Certified Solutions Architect - Professional",
        "AWS Certified Developer - Associate",
        "AWS Certified CloudOps Engineer - Associate",
        "AWS Certified DevOps Engineer - Professional",
        "AWS Certified Security - Specialty",
        "AWS Certified Machine Learning Engineer - Associate",
        "AWS Certified Data Engineer - Associate",
        "AWS Certified Advanced Networking - Specialty",
        "Microsoft Certified: Azure Fundamentals",
        "Microsoft Certified: Azure AI Fundamentals",
        "Microsoft Certified: Azure Data Fundamentals",
        "Microsoft Certified: Azure Administrator Associate",
        "Microsoft Certified: Azure Developer Associate",
        "Microsoft Certified: Azure Solutions Architect Expert",
        "Microsoft Certified: DevOps Engineer Expert",
        "Microsoft Certified: Security Operations Analyst Associate",
        "Microsoft Certified: Cybersecurity Architect Expert",
        "Microsoft Certified: Power BI Data Analyst Associate",
        "Google Cloud Digital Leader",
        "Google Cloud Generative AI Leader",
        "Google Associate Cloud Engineer",
        "Google Professional Cloud Architect",
        "Google Professional Cloud Developer",
        "Google Professional Cloud DevOps Engineer",
        "Google Professional Cloud Security Engineer",
        "Google Professional Cloud Network Engineer",
        "Google Professional Data Engineer",
        "Google Professional Machine Learning Engineer",
        "Oracle Cloud Infrastructure Foundations Associate",
        "Oracle Cloud Infrastructure Architect Associate",
        "Oracle Cloud Infrastructure Architect Professional",
        "Oracle Cloud Infrastructure Developer Professional",
        "Oracle Cloud Infrastructure DevOps Professional",
        "Oracle Cloud Infrastructure Security Professional",
        "Alibaba Cloud ACA Cloud Computing",
        "Alibaba Cloud ACP Cloud Computing",
        "Alibaba Cloud ACE Cloud Computing",
        "Alibaba Cloud ACA Cloud Security",
        "Alibaba Cloud ACP Cloud Security",
        "Alibaba Cloud ACA Big Data",
        "Alibaba Cloud ACP Big Data",
        "Tencent Cloud Practitioner",
        "Tencent Cloud Associate Cloud Computing",
        "Tencent Cloud Professional Cloud Architect",
        "Tencent Cloud Professional Cloud Security",
        "Tencent Cloud Professional Big Data",
        "Tencent Cloud Professional AI",
    ],
    "华为 ICT 认证": [
        "HCIA-Datacom",
        "HCIP-Datacom",
        "HCIE-Datacom",
        "HCIA-Security",
        "HCIP-Security",
        "HCIE-Security",
        "HCIA-Cloud Computing",
        "HCIP-Cloud Computing",
        "HCIE-Cloud Computing",
        "HCIA-Cloud Service",
        "HCIP-Cloud Service",
        "HCIA-AI",
        "HCIP-AI",
        "HCIA-Big Data",
        "HCIP-Big Data",
        "HCIE-Big Data",
        "HCIA-Storage",
        "HCIP-Storage",
        "HCIE-Storage",
        "HCIA-GaussDB",
        "HCIP-GaussDB",
        "HCIA-openEuler",
        "HCIP-openEuler",
    ],
    "网络、安全与攻防": [
        "Cisco CCST Networking",
        "Cisco CCST Cybersecurity",
        "Cisco CCNA",
        "Cisco CCNP Enterprise",
        "Cisco CCNP Security",
        "Cisco CCNP Data Center",
        "Cisco CCIE Enterprise Infrastructure",
        "Cisco CCIE Security",
        "Cisco DevNet Associate",
        "Cisco DevNet Professional",
        "CompTIA A+",
        "CompTIA Network+",
        "CompTIA Security+",
        "CompTIA CySA+",
        "CompTIA PenTest+",
        "CompTIA SecurityX",
        "CompTIA Cloud+",
        "CompTIA Linux+",
        "CompTIA Server+",
        "ISC2 Certified in Cybersecurity",
        "ISC2 SSCP",
        "ISC2 CISSP",
        "ISC2 CCSP",
        "ISC2 CSSLP",
        "ISACA CISA",
        "ISACA CISM",
        "ISACA CRISC",
        "ISACA CDPSE",
        "EC-Council CEH",
        "EC-Council CHFI",
        "EC-Council CND",
        "EC-Council CPENT",
        "Offensive Security OSCP",
        "CISP 注册信息安全专业人员",
        "CISP-PTE 注册渗透测试工程师",
        "CISP-PTS 注册渗透测试专家",
        "CISAW 信息安全保障人员认证",
    ],
    "Linux、DevOps 与云原生": [
        "Red Hat Certified System Administrator",
        "Red Hat Certified Engineer",
        "Red Hat Certified Architect",
        "Red Hat Certified OpenShift Administrator",
        "Red Hat Certified OpenShift Application Developer",
        "Red Hat Certified Specialist in OpenShift Virtualization",
        "Linux Foundation Certified IT Associate",
        "Linux Foundation Certified System Administrator",
        "Linux Foundation Certified Engineer",
        "Certified Kubernetes Administrator",
        "Certified Kubernetes Application Developer",
        "Certified Kubernetes Security Specialist",
        "Kubernetes and Cloud Native Associate",
        "Kubernetes and Cloud Security Associate",
        "HashiCorp Certified: Terraform Associate",
        "HashiCorp Certified: Vault Associate",
        "Docker Certified Associate",
        "GitLab Certified CI/CD Associate",
        "GitHub Actions Certification",
    ],
    "数据库、数据分析与 AI": [
        "Oracle Database SQL Certified Associate",
        "Oracle Database Administration I",
        "Oracle Database Administration II",
        "Oracle MySQL 8.0 Database Administrator",
        "Oracle MySQL 8.0 Database Developer",
        "Oracle Java SE 8 Programmer I",
        "Oracle Java SE 8 Programmer II",
        "Oracle Java SE 11 Developer",
        "Oracle Java SE 17 Developer",
        "Oracle Java SE 21 Developer Professional",
        "MongoDB Associate Developer",
        "MongoDB Associate Database Administrator",
        "Snowflake SnowPro Core",
        "Snowflake Advanced Data Engineer",
        "Snowflake Advanced Data Scientist",
        "Databricks Certified Data Engineer Associate",
        "Databricks Certified Data Engineer Professional",
        "Databricks Certified Data Analyst Associate",
        "Databricks Certified Machine Learning Associate",
        "Tableau Desktop Specialist",
        "Tableau Certified Data Analyst",
        "SAS Certified Specialist: Base Programming",
        "SAS Certified Professional: Advanced Programming",
        "CDMP 数据管理专业人士",
        "IIBA-CBDA 商业数据分析认证",
        "阿里云 ACA 人工智能",
        "阿里云 ACP 人工智能",
        "百度智能云 AI 工程师认证",
        "华为 AI 工程师认证",
    ],
}
CERTIFICATES = [cert for items in CERTIFICATE_GROUPS.values() for cert in items]
SCENARIOS = ["智能制造", "智慧教育", "金融风控", "政务数据治理", "工业物联网", "企业知识库", "内容审核", "数据资产运营", "智慧城市", "数字化转型"]
